# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a026ea230207e0e1e0587a5cc9f8e3da2da0cdcc94de8b87c59f72d856fab3c17d661762ff640265aec35972504112f8bdc763118bd2f4861929876068f062d

test:
  secret_key_base: 6cb8dc369e595dfb76da8eb40997e3e28cdf006e201f41b56cd14b682cd6c6d0e65f95405f98f6e82c54c2b25c221bf86ac03960979bdf0d74b8e3d355b44b7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
